version: '2'

services:
  gogs:
    image: gogs/gogs:0.11.4
    ports:
      - "10022:22"
      - "10080:3000"
    volumes:
      - /var/gogs:/data
    restart: always

  drone-server:
    image: drone/drone:0.7.1
    ports:
      - 80:8000
    volumes:
      - ./drone:/var/lib/drone/
    restart: always
    environment:
      - DRONE_OPEN=true
      - DRONE_GOGS=true
# DRONE_HOST may not be needed
      - DRONE_HOST=http://drone-server:8000
      - DRONE_GOGS_URL=http://gogs:3000
      - DRONE_SECRET=${DRONE_SECRET}

  drone-agent:
    image: drone/drone:0.7.1
    command: agent
    restart: always
    depends_on: [ drone-server ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=ws://drone-server:8000/ws/broker
      - DRONE_SECRET=${DRONE_SECRET}
