---
- name: Install git
  apt: name=git state=present

- name: Install tree
  apt: name=tree state=present

- name: Install ag
  apt: name=silversearcher-ag state=present

- name: Install jq
  apt: name=jq state=present

- name: Install autojump
  apt: name=autojump state=present
  register: autojump_status

- name: Install vim
  apt: name=vim state=present

- name: copy autojump profile
  copy:
    src=/usr/share/autojump/autojump.sh
    dest=/etc/profile.d/autojump.sh
  when: autojump_status.changed
